server:
  port: 8080
  servlet:
    session:
      timeout: 600000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_HIBERNATE_SHOW_SQL}
    database: postgresql

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: ${SPRING_SESSION_JDBC_INITIALIZE_SCHEMA}
      table-name: SPRING_SESSION

  mail:
    host: smtp.naver.com
    port: 465
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true


logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
