server:
  port: 8080
  servlet:
    session:
      timeout: 600000
      tracking-modes: cookie

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  cache:
    type: redis
  redis:
    host: ${redis.cache.host}
    port: ${redis.cache.port}

  session:
    store-type: redis
    jdbc:
      initialize-schema: embedded
      table-name: SPRING_SESSION

  mail:
    host: smtp.naver.com
    port: 465
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    s3:
      bucket: ${aws.s3.bucket}
    credentials:
      access-key: ${aws.credentials.accesskey}
      secret-key: ${aws.credentials.secretkey}
    region:
      static: ${aws.region.static}
      auto: false
    stack:
      auto: false

logging:
  level:
    org.hibernate.sql: debug
#    org.hibernate.type: trace
